# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a326d9e2b90f821a76a3f63f4013a2fbbeb572db5c2363c016a44c272fff4dd5a9c075fe3fddd8c393d0ec471d665d699e7273a023dff20b76736707e4182f2a
  telegram:
    bot: 
      token: 272987442:AAFotXv-xTMLwpWg_X4LLtFGMJt4hBOl_aE
      username: tbgemtest_bot

test:
  secret_key_base: 05d2808e9d40ce2f3912ff3d508f64d98231d8a32d9d66c9eddb009c393d66c6a5ab6d6f61a7bc507a01b5100ebf5f6346798096a0886433ebd9c988042af7d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


